version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/node-blog-api"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/react-blog"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/react-admin"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/react-music-app"
    update_schedule: "live"